# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170526_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliouser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
