# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rental_who'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'permissions': (('can_rent', 'Can rent a book'),)},
        ),
    ]
