# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20170520_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
    ]
