# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_auto_20170521_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedition',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='shelf.Book'),
        ),
    ]
